services:
  flask:
    build: ./Server
    container_name: flask_server
    volumes:
      - ./Storage:/Storage
    ports:
      - "8080:8080"
    networks:
      - webnet

  discord_bot:
    build: ./Bot
    container_name: discord_bot
    volumes:
      - ./Storage:/Storage
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
    networks:
      - webnet

networks:
  webnet:
    driver: bridge